# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
     
      # Runs a set of commands using the runners shell
      - name: SSH access and deploy
        env:
          SSH_KEY     : ${{ secrets.SVAP01_SSH_PRIVATE_KEY }}
          SSH_NAME    : ${{ secrets.SVAP01_SSH_NAME }}
          SSH_PORT    : ${{ secrets.SVAP01_SSH_PORT }}
          SSH_HOST    : ${{ secrets.SVAP01_SSH_HOST }}
          SSH_CMD     : ${{ secrets.SVAP01_SSH_CMD  }}
        run: |
          echo 
          echo "$SSH_KEY" > secret_key
          chmod 600 secret_key
          ssh -oStrictHostKeyChecking=no ${SSH_NAME}@${SSH_HOST} -p ${SSH_PORT} -i secret_key "$SSH_CMD"
          echo success!!
